site_name: sousafx
site_url: https://rnbo.sousastep.quest/
nav:
  - Intro: index.md
  - Hardware: hardware.md
  - Setup: setup.md
  - Installation: installation.md
  - Overview: overview.md
  - Loopers: loopers.md
  - Bindings: bindings.md
  - Purchase: purchase.md
  - Prestige: prestige.md
  - EULA: eula.md
  - Modding: modding.md
  - Attributions: attributions.md

theme:
  name: material
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer

  logo: img/logo.png
  favicon: img/favicon.ico

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/linktree
      link: https://www.sousastep.quest/links/
    - icon: fontawesome/brands/github
      link: https://github.com/jbaylies
    - icon: fontawesome/brands/discord
      link: https://discord.gg/JkSQzfZUdT

plugins:
  - search
  - open-in-new-tab
  - autorefs
  - glightbox

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
