site_name: sousafx
site_url: https://rnbo.sousastep.quest/
site_description: >-
  SousaFX is a multi-effects audio rig for tuba and didgeridoo players to perform dubstep and wobble-bass genres. Control auto-wah, filters, loopers, drums, delays, and stutters with a game controller.
nav:
  - Introduction: index.md
  - Hardware: hardware.md
  - Installation: installation.md
  - Documentation: documentation.md
  - Overview: overview.md
  - Bindings: bindings.md
  - Loopers: loopers.md
  - Release Notes: releasenotes.md
  - Purchase: purchase.md
  - Modding: modding.md
  - Attributions: attributions.md
  - Recommended Media: recommended_media.md

theme:
  name: material
  custom_dir: overrides
  language: en
  palette:
    scheme: slate
    primary: black

  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer

  logo: img/logo.png
  favicon: img/favicon.ico

extra:
  analytics:
    provider: google
    property: G-YMBTS82PVP
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/linktree
      link: https://www.sousastep.quest/links/
    - icon: fontawesome/brands/github
      link: https://github.com/jbaylies
    - icon: fontawesome/brands/discord
      link: https://discord.gg/JkSQzfZUdT

plugins:
  - search
  - open-in-new-tab
  - autorefs
  - offline:
      enabled: !ENV [OFFLINE, false]

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - attr_list
  - md_in_html
  - def_list

